config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'projects#index'

  resources :pages

  resources :profiles, only: [:index, :show, :create, :edit, :update]

  resources :projects do
    resources :jobs, only: [:index, :new, :create, :edit, :update]
  end

  resources :jobs, only: [:show, :destroy] do
    resources :user_jobs, only: [:show, :new, :create, :edit, :update]
  end

  resources :user_jobs, only: [:index]

  resources :signatures, only: :create

  get '/overview', to: 'projects#overview'

  get '/auth/:provider/callback', to: 'ds_common#create_session'

  get '/ds/mustAuthenticate' => 'ds_common#ds_must_authenticate'

  # get '/uikit', to: 'pages#uikit'
  # get '/sitemap', to: 'pages#sitemap'
  # get '/profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  # post '/profiles', to: 'profiles#update', as: 'create_profile'
  # patch '/profiles/:id', to: 'profiles#update', as: 'update_profile'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_job.rb
class UserJob < ApplicationRecord
  belongs_to :job
  belongs_to :user
  validate :check_if_user_is_available, on: :create

  def start_time
    self.job.start_date
  end

  def end_time
    self.job.end_date
  end

  private

  def check_if_user_is_available
    # unavailable_dates is an array of TimeWithZone ranges
    unavailable_dates = user.unavailable_dates

    # when is this job?
    job_dates = (job.start_date.to_date)..(job.end_date.to_date)

    job_dates.each do |date|
      unavailable_dates.each do |unavailable_range|
        if unavailable_range.include? date
          errors.add(:user, "is not available on #{date}")
        end
      end
    end

  end
end

app/controllers/user_jobs_controller.rb
class UserJobsController < ApplicationController
  def index
    # if params[:signature] == 'success'
    #   flash[:messages] = "Your contract has been signed successfully."
    # end

    @user_jobs = UserJob.where(user: current_user)
    @approved = @user_jobs.where(status: 'Approved')
    @applied = @user_jobs.where(status: 'Applied')
    @confirmed = @user_jobs.where(status: 'Confirmed')
    @rejected = @user_jobs.where(status: 'Rejected')
    @calendar_events = @user_jobs.where.not(status: 'Rejected')
    @notifications = current_user.notifications.unread
  end

  def show
    @user_job = UserJob.find(params[:id])
    session[:ds_user_job_to_sign] = @user_job.id

    @config = Rails.application.config

    @token_ok = check_token
    # check if the user is authenticated on Docusign
    if @token_ok
      # do crazy shit and then render the view
      # addSpecialAttributes(model)
      @envelope_ok = session[:envelope_id].present?
      @documents_ok = session[:envelope_documents].present?
      @document_options = session.fetch(:envelope_documents, {})['documents']
      @gateway_ok = @config.gateway_account_id.try(:length) > 25
      @template_ok = session[:template_id].present?
      @source_file = file_name.to_s
      @source_url = "#{@config.github_example_url}#{@source_file}"
      @documentation = "#{@config.documentation}#{eg_name}" #= Config.documentation + EgName
      @show_doc = @config.documentation
    elsif @config.quickstart == true
      redirect_to '/ds/mustAuthenticate'
    else
      # RequestItemsService.EgName = EgName
      redirect_to '/ds/mustAuthenticate'
    end

    if params[:signature] == 'success'
      @user_job.status = "Confirmed"
      @user_job.save

      applicant = @user_job.user
      all_jobs = applicant.jobs
      conflicting_jobs = all_jobs.where("(start_date < ? AND end_date > ?) OR (start_date > ? AND end_date < ?)", @user_job.job.start_date, @user_job.job.end_date, @user_job.job.start_date, @user_job.job.end_date)
      conflicting_user_jobs = conflicting_jobs.map do |job|
        # need to convert job instances into user_job instances
        # where user = applicant
        job.user_jobs.where(user: applicant).first
      end
      conflicting_user_jobs.each { |user_job| user_job.update(status: "Rejected") }
      # Other jobs where the user is the confirmed_job user, and status is applied or approved
      # if the other user jobs start after or equals to confirmed job start date,
      # and end before or equals to confirmed job end date
      # status will change to rejected (or other job taken)
      redirect_to user_jobs_path
    end
  end

  def new
    @user = current_user
    @job = Job.find(params[:job_id])
    @user_job = UserJob.new
  end

  def create
    if current_user.profile.nil?
      notification = CommentNotification.with(comment: "Please complete your profile first.")
      notification.deliver(current_user)
      redirect_to edit_profile_path

    else
      job = Job.find(params[:job_id])
      @user_job = UserJob.new(status: "Applied")
      @user_job.job = job
      @user_job.user = current_user

      if @user_job.save
        notification = CommentNotification.with(comment: "New application for #{@user_job.job.project.title}")
        notification.deliver(@user_job.job.project.user)
        redirect_to project_path(job.project)
      else
        notification = CommentNotification.with(comment: "You already have a confirmed project during these dates.")
        notification.deliver(current_user)
      end
    end
  end

  def edit
    @user_job = UserJob.find_by(job_id: params[:job_id], id: params[:id])
  end

  def update
    @user_job = UserJob.find_by(job_id: params[:job_id], id: params[:id])
    @user_job.update(user_job_params)
    if @user_job.save
      notification = CommentNotification.with(comment: "Your application status for #{@user_job.job.project.title} is now #{@user_job.status}.")
      notification.deliver(@user_job.user)
      redirect_to overview_path
    else
      render :edit
    end
  end

  private

  def check_token(buffer_in_min = 10)
    buffer = buffer_in_min * 60
    expires_at = session[:ds_expires_at]
    remaining_duration = expires_at.nil? ? 0 : expires_at - buffer.seconds.from_now.to_i
    if expires_at.nil?
      Rails.logger.info "==> Token expiration is not available: fetching token"
    elsif remaining_duration.negative?
      Rails.logger.debug "==> Token is about to expire in #{time_in_words(remaining_duration)} at: #{Time.at(expires_at)}: fetching token"
    else
      Rails.logger.debug "==> Token is OK for #{time_in_words(remaining_duration)} at: #{Time.at(expires_at)}"
    end
    remaining_duration > 0
  end

  def file_name
    File.basename __FILE__
  end

  def time_in_words(duration)
    "#{Object.new.extend(ActionView::Helpers::DateHelper).distance_of_time_in_words(duration)}#{duration.negative? ? ' ago' : ''}"
  end

  def eg_name
    controller_name.to(4)
  end

  def user_job_params
    params.require(:user_job).permit(:status)
  end
end

app/views/user_jobs/_user_jobs_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>

          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>

              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>

            <% end %>
          <% end %>

        </tr>
      <% end %>
    </tbody>

  </table>

</div>

app/views/user_jobs/edit.html.erb
<h2><strong>EDIT STATUS</strong></h2>

<p>Project: <%= @user_job.job.project.title %></p>
<p>Job: <%= @user_job.job.title %></p>
<p class="my-1">Applicant: <%= @user_job.user.profile.first_name.capitalize %> <%= @user_job.user.profile.last_name.capitalize %></p>
<%= link_to "View Profile", profile_path(@user_job.user.profile), class: 'btn btn-primary m-0'  %>

<%= simple_form_for(@user_job, url: job_user_job_path, method: :patch) do |f| %>
  <div class="form-inputs type-form-control">
    <%= f.input :status, label: 'Status:', as: :radio_buttons, collection: %w(Applied Approved Rejected), class: "form-check-label"%>
  </div>
  <div class="form-actions">
    <%= f.submit "Update Status", class: "btn btn-flat" %>
  </div>
<% end %>

app/views/user_jobs/index.html.erb
<h1>My Jobs</h1>

<%= UserJobsCalendar.new(self, events: @calendar_events).render do |date, user_jobs| %>
  <%= date.day %>
<% end %>

<% @notifications.each do |notification| %>
  <div class="alert alert-warning" role="alert">
    <p><%= render notification %></p>
  </div>
<% end %>

<h3>Applied</h3>
<% @applied.each do | user_job | %>
  <div class="submissions">
    <%= link_to project_path(user_job.job.project) do%>
      <h5><%= user_job.job.project.title %></h5>
    <% end %>
    <p>Job Title: <%= user_job.job.title %> </p>
    <p>Job Dates: <%= "#{user_job.job.start_date.strftime('%d %b %Y')} to #{user_job.job.end_date.strftime('%d %b %Y')}" %></p>
    <p>Job Status: <%= user_job.status %> </p>
  </div>
<% end %>

<h3>Approved</h3>
<% @approved.each do | user_job | %>
  <div class="submissions">
    <%= link_to project_path(user_job.job.project) do%>
      <h5><%= user_job.job.project.title %></h5>
    <% end %>
    <p>Job Title: <%= user_job.job.title %> </p>
    <p>Job Dates: <%= "#{user_job.job.start_date.strftime('%d %b %Y')} to #{user_job.job.end_date.strftime('%d %b %Y')}" %></p>
    <p>Job Status: <%= user_job.status %> </p>
    <%= link_to "Go to Project Acceptance Page", job_user_job_path(user_job.job, user_job), class: 'btn btn-success w-100 m-0'  %>
  </div>
<% end %>

<h3>Confirmed</h3>
<% @confirmed.each do | user_job | %>
  <div class="submissions">
    <%= link_to project_path(user_job.job.project) do%>
      <h5><%= user_job.job.project.title %></h5>
    <% end %>
    <p>Job Title: <%= user_job.job.title %> </p>
    <p>Job Dates: <%= "#{user_job.job.start_date.strftime('%d %b %Y')} to #{user_job.job.end_date.strftime('%d %b %Y')}" %></p>
    <p>Job Status: <%= user_job.status %> </p>
  </div>
<% end %>

<h3>Rejected</h3>
<% @rejected.each do | user_job | %>
  <div class="submissions">
    <%= link_to project_path(user_job.job.project) do%>
      <h5><%= user_job.job.project.title %></h5>
    <% end %>
    <p>Job Title: <%= user_job.job.title %> </p>
    <p>Job Dates: <%= "#{user_job.job.start_date.strftime('%d %b %Y')} to #{user_job.job.end_date.strftime('%d %b %Y')}" %></p>
    <p>Job Status: <%= user_job.status %> </p>
  </div>
<% end %>

<%= link_to "Back", :back, class: 'btn btn-flat'  %>
<%= link_to "Go to All Projects", root_path, class: 'btn btn-flat'  %>

app/views/user_jobs/show.html.erb
<h3>Accept <%= @user_job.job.title %> Job for <%= @user_job.job.project.title %></h3>

<form class="eg" id="data_form" action="/signatures" method="post" data-busy="form">

  <div class="form-group form-inputs type-form-control">
    <label for="signerEmail">Signer Email</label>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="email" class="form-control" id="signerEmail" name="signerEmail"
           aria-describedby="emailHelp" placeholder="pat@example.com" required
           value="<%= @config.signer_email %>">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>

  <div class="form-group  form-inputs type-form-control">
    <label for="signerName">Signer Name</label>
    <input type="text" class="form-control" id="signerName" placeholder="Pat Johnson" name="signerName"
           value="<%= @config.signer_name %>" required>
  </div>

  <button type="submit" class="btn btn-flat w-100">Submit</button>

</form>