config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'projects#index'

  resources :pages

  resources :profiles, only: [:index, :show, :create, :edit, :update]

  resources :projects do
    resources :jobs, only: [:index, :new, :create, :edit, :update]
  end

  resources :jobs, only: [:show, :destroy] do
    resources :user_jobs, only: [:show, :new, :create, :edit, :update]
  end

  resources :user_jobs, only: [:index]

  resources :signatures, only: :create

  get '/overview', to: 'projects#overview'

  get '/auth/:provider/callback', to: 'ds_common#create_session'

  get '/ds/mustAuthenticate' => 'ds_common#ds_must_authenticate'

  # get '/uikit', to: 'pages#uikit'
  # get '/sitemap', to: 'pages#sitemap'
  # get '/profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  # post '/profiles', to: 'profiles#update', as: 'create_profile'
  # patch '/profiles/:id', to: 'profiles#update', as: 'update_profile'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom navbar-expand-sm navbar-dark navbar-lewagon">
  <span id="user-id" class="d-none" data-user-id="<%= current_user.id if user_signed_in? %>"></span>
  <% if user_signed_in? %>
    <%= link_to root_path, class: "nav-link" do %>
      <i class="fas fa-home"></i>
    <% end %>

    <% if current_user.is_producer? %>

      <%= link_to overview_path, class: "nav-link" do %>

        <% if current_user.notifications.unread.empty? %>
          <i class="fas fa-clipboard-list"></i>
          <i class="fas fa-circle navbar-badge d-none"></i>
        <% else %>
          <i class="fas fa-clipboard-list"></i>
          <i class="fas fa-circle navbar-badge"></i>
        <% end %>

      <% end %>

      <%= link_to new_project_path, class: "nav-link" do %>
        <i class="fas fa-plus"></i>
      <% end %>

    <% else %>

      <%= link_to user_jobs_path, class: "nav-link" do %>

        <% if current_user.notifications.unread.empty? %>
          <i class="fas fa-clipboard-list"></i>
          <i class="fas fa-circle navbar-badge d-none"></i>
        <% else %>
          <i class="fas fa-clipboard-list"></i>
          <i class="fas fa-circle navbar-badge"></i>
        <% end %>

      <% end %>

    <% end %>

    <% if current_user.profile.nil? %>

      <%= link_to edit_profile_path(current_user), class: "nav-link" do %>
          <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/599/599305.svg", width: 25, height: 25, crop: :fill, class: "avatar-card"%>
      <% end %>

    <% else %>

      <%= link_to profile_path(current_user.profile), class: "nav-link" do %>

        <% if current_user.profile.photo.attached? %>
          <%= cl_image_tag current_user.profile.photo.key, width: 25, height: 25, crop: :fill, class: "avatar-card" %>
        <% else %>
          <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/599/599305.svg", width: 25, height: 25, crop: :fill, class: "avatar-card"%>
        <% end %>

      <% end %>

    <% end %>

    <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
      <i class="fas fa-sign-out-alt"></i>
    <% end %>

  <% else %>

    <%= link_to "Login", new_user_session_path, class: "btn nav-link" %>
    <%= link_to root_path, class: "nav-link" do %>
      <i class="fas fa-home"></i>
    <% end %>
    <%= link_to "Sign Up",  new_user_registration_path , class: "btn nav-link" %>

  <% end %>
</div>

<% unless @notification.nil? do %>
    <% @notifications.each do |notification| %>
      <div class="alert alert-warning" role="alert">
        <p><%= render notification %></p>
      </div>
    <% end %>
  <% end %>
<% end %>