config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'projects#index'

  resources :pages

  resources :profiles, only: [:index, :show, :create, :edit, :update]

  resources :projects do
    resources :jobs, only: [:index, :new, :create, :edit, :update]
  end

  resources :jobs, only: [:show, :destroy] do
    resources :user_jobs, only: [:show, :new, :create, :edit, :update]
  end

  resources :user_jobs, only: [:index]

  resources :signatures, only: :create

  get '/overview', to: 'projects#overview'

  get '/auth/:provider/callback', to: 'ds_common#create_session'

  get '/ds/mustAuthenticate' => 'ds_common#ds_must_authenticate'

  # get '/uikit', to: 'pages#uikit'
  # get '/sitemap', to: 'pages#sitemap'
  # get '/profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  # post '/profiles', to: 'profiles#update', as: 'create_profile'
  # patch '/profiles/:id', to: 'profiles#update', as: 'update_profile'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/sitemap.html.erb
<h1>Welcome to CrewCall Sitemap (for easy links)</h1>

<p><%= link_to "UIKit", uikit_path, class: "btn btn-flat" %></p>
<p><%= link_to "Profiles Index", profiles_path, class: "btn btn-flat" %></p>
<p><%= link_to "Profiles New", new_profile_path, class: "btn btn-flat" %></p>
<p><%= link_to "Projects Index", projects_path, class: "btn btn-flat" %></p>
<p><%= link_to "Projects New", new_project_path, class: "btn btn-flat" %></p>

app/views/pages/uikit.html.erb
<h1>Welcome to CrewCall UIKit</h1>

<h3 class='text-centre'>Search Field</h3>

<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required px-4" type="text" name="search[query]" id="search_query", placeholder="Search" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>


<h3>Type Field</h3>
<div class="type-form-control form-group">
    <input class="form-control string required px-4" type="text" name="message" id="message" placeholder="Send a Message" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="far fa-paper-plane"></i>
    </button>
  </div>

<h3>Project Card</h3>

<div class="card-product">
  <img class="project-image" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-product-infos">
    <h2>Project name</h2>
    <p>Project description with <strong>relevant info</strong> only.</p>
  </div>
</div>


<h3>Buttons</h3>

<%= link_to "Book now", "#", class: "btn btn-flat" %>
<i class="fab fa-twitter"></i>
<i class="fab fa-facebook"></i>
<i class="fab fa-linkedin"></i>
<i class="fab fa-instagram"></i>

<h3>Avatar</h3>

<%= image_tag "https://kitt.lewagon.com/placeholder/users/cveneziani", class: "avatar", alt: "avatar" %>


<h3>Bottom Nav Bar</h3>