config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'projects#index'

  resources :pages

  resources :profiles, only: [:index, :show, :create, :edit, :update]

  resources :projects do
    resources :jobs, only: [:index, :new, :create, :edit, :update]
  end

  resources :jobs, only: [:show, :destroy] do
    resources :user_jobs, only: [:show, :new, :create, :edit, :update]
  end

  resources :user_jobs, only: [:index]

  resources :signatures, only: :create

  get '/overview', to: 'projects#overview'

  get '/auth/:provider/callback', to: 'ds_common#create_session'

  get '/ds/mustAuthenticate' => 'ds_common#ds_must_authenticate'

  # get '/uikit', to: 'pages#uikit'
  # get '/sitemap', to: 'pages#sitemap'
  # get '/profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  # post '/profiles', to: 'profiles#update', as: 'create_profile'
  # patch '/profiles/:id', to: 'profiles#update', as: 'update_profile'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  before_destroy :purge_photo
  before_create :assign_color
  has_one_attached :photo
  has_rich_text :rich_description
  belongs_to :user
  has_many :jobs, dependent: :destroy
  validates :title, presence: true, length: { maximum: 70 }

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  include PgSearch::Model
  pg_search_scope :search_by_project,
  against: [:title, :description],
  using: {
    tsearch: { prefix: true }
  }

  def start_time
    self.start_date
  end

  def end_time
    self.end_date
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

  def purge_photo
    photo.purge
  end

  def assign_color
    if user.projects.empty?
      self.color = 1
    else
      self.color = (self.user.projects.order(:created_at).last.color % 4) + 1
    end
  end
end

app/controllers/projects_controller.rb
require 'open-uri'

class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query]
      @projects = Project.search_by_project(params[:query]).order(updated_at: :desc)
    else
      @projects = Project.all.order(updated_at: :desc)
    end
  end

  def show
    render layout: 'no-container'
  end

  def new
    if current_user.profile.nil?
      notification = CommentNotification.with(comment: "Please complete your profile first.")
      notification.deliver(current_user)
      redirect_to edit_profile_path
    else
      @project = Project.new
      @jobs = Job.where(project: @project)
    end
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      if project_params[:photo].nil?
        url = "https://source.unsplash.com/720x480/?filmmaking"
        image = URI.open(url)
        @project.photo.attach(io: image, filename: "project_#{@project.id}.jpeg", content_type: 'image/jpeg')
      end
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    if @project.save
      if project_params[:photo].nil?
        url = "https://source.unsplash.com/720x480/?filmmaking"
        image = URI.open(url)
        @project.photo.attach(io: image, filename: "project_#{@project.id}.jpeg", content_type: 'image/jpeg')
      end
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to overview_path
  end

  def overview
    @projects = Project.where(user: current_user)
    @notifications = current_user.notifications.unread
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :photo, :start_date, :end_date, :rich_description)
  end
end

app/views/projects/_producers_calendar.html.erb
<div class="simple-calendar">

  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">

    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>

          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>

        </tr>
      <% end %>
    </tbody>

  </table>

</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= simple_form_for([@project]) do |f| %>
  <div class="form-inputs type-form-control">
    <%= f.input :title %>
    <p>Description</p>
    <%= f.rich_text_area :rich_description, required: true, label: "Description" %>
    <%= f.input :start_date, label: "Start Date", as: :string, type: :text %>
    <%= f.input :end_date, label: "End Date", as: :string, type: :text %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.submit "Update", class: "btn btn-flat" %>
  </div>

<% end %>

<p><%= link_to "Delete #{@project.title} Project",
      project_path(@project),
      class: 'btn btn-danger',
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>

app/views/projects/index.html.erb
<div class="header mb-1">
  <%= image_tag ("CrewcallLogo2.png"), height: 45%>
  <h2 class="my-2 ml-1" style="font-size: revert;">CREWCALL</h2>
</div>

<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required px-4" type="text" name="query" id="search_query", placeholder="Search" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>


<div>
  <% @projects.each do |project| %>

    <%= link_to project_path(project) do %>
      <div class="card-product mt-2">
        <%= cl_image_tag project.photo.key, gravity: :auto, class: "project-image" %>

        <div class="card-product-infos">
          <h2><%= project.title %></h2>
          <p><%= "#{project.start_date.strftime('%d %b %Y')} to #{project.end_date.strftime('%d %b %Y')}" %></p>

            <%= link_to profile_path(project.user.profile) do %>

              <% if project.user.profile.photo.attached? %>
                <%= cl_image_tag project.user.profile.photo.key, width: 25, height: 25, crop: :fill, class: "avatar-card" %>
              <% else %>
                <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/599/599305.svg", width: 25, height: 25, crop: :fill, class: "avatar-card"%>
              <% end %>

            <div class="card-avatar-infos">
              <%= project.user.username %>
            </div>
          <% end %>
       </div>

      </div>
    <% end %>

  <% end %>
</div>

<div>
  <%= link_to "View Profiles", profiles_path, class: 'btn btn-flat fw-light'  %>
</div>

app/views/projects/new.html.erb
<h1>Start a new Project</h1>

<%= simple_form_for([@project]) do |f| %>
  <div class="form-inputs type-form-control">
    <%= f.input :title %>
    <p>Description</p>
    <%= f.rich_text_area :rich_description, required: true, label: "Description" %>
    <%= f.input :start_date, label: "Start Date", as: :string, type: :text %>
    <%= f.input :end_date, label: "End Date", as: :string, type: :text %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.submit "Create a Project", class: "btn btn-flat w-100" %>
  </div>

<% end %>

app/views/projects/overview.html.erb
<h1>Overview</h1>

<%= ProducersCalendar.new(self, events: @projects).render do |date, projects| %>
  <%= date.day %>
<% end %>

<% @projects.each do |project| %>
  <div class="submissions">
    <div class="d-flex text-right">
      <h5 class="text-left"><%= project.title %></h5>
      <p><%= link_to "Edit", edit_project_path(project), class: 'btn btn-warning' %></p>
    </div>
    <p><%= "#{project.start_date.strftime('%d %b %Y')} to #{project.end_date.strftime('%d %b %Y')}" %></p>
    <p><%= link_to "See All Jobs Applicants", project_jobs_path(project), class: 'btn btn-success w-100 m-0' %></p>
  </div>
<% end %>

<%= link_to "Back", :back, class: 'btn btn-flat'  %>

app/views/projects/show.html.erb
<div class="rounded border">
  <% if @project.photo.attached? %>
    <%= cl_image_tag @project.photo.key, height: 200, crop: :fill, class: "photobanner" %>
  <% end %>
</div>

<div class="container">

  <div class="pt-2">
    <h3><strong><%= @project.title.upcase %></strong></h3>
  </div>

  <div class="usernameheader d-flex justify-content-between">
    <div>
      <%= link_to profile_path(@project.user.profile) do %>
        <% if @project.user.profile.photo.attached? %>
          <%= cl_image_tag @project.user.profile.photo.key, width: 25, height: 25, crop: :fill, class: "avatar"%>
        <% else %>
          <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/599/599305.svg", width: 25, height: 25, crop: :fill, class: "avatar" %>
        <% end %>
        <%= @project.user.username %>
      <% end %>
    </div>
  </div>

  <h4 class= "mt-3">About the Project</h4>
  <%= @project.rich_description %>

  <div class="projcontainer">
    <h4>Project Timeline</h4>
    <p><%= @project.start_date.strftime('%d %b %Y') %> to <%= @project.end_date.strftime('%d %b %Y') %></p>
  </div>

  <div class="projcontainer">
    <h4>Project Jobs</h4>

    <% if @project.jobs.exists? %>
      <div>
        <% @project.jobs.each do |job| %>
          <div class="jobcard">
            <div class="jobcard-info">
              <p class="job-title"><%= job.title %></p>
              <p class="job-dept badge rounded-pill bg-light text-dark px-2"><%= job.department %></p>
              <%= job.rich_description %>
              <% if current_user == @project.user %>
                <div class="btn-abc">
                  <%= link_to "Edit Job", edit_project_job_path(@project, job), class: 'btn btn-primary' %>
                  <%= link_to "Delete Job",
                      job_path(job),
                      class: 'btn btn-danger',
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>
                </div>
              <% end %>
            </div>

            <div class="jobcard-info-glance">
              <div><p>Salary</p> <p>$<%= job.salary / 100 %> per Day</p></div>
              <div><p>Start Date</p> <p><%= job.start_date.strftime('%d %b %Y') %></p></div>
              <div><p>End Date</p> <p><%= job.end_date.strftime('%d %b %Y') %></p></div>
            </div>

            <% if user_signed_in? %>
              <% user_job = UserJob.find_by(job: job.id, user: current_user) %>

              <% if user_job.nil? %>

                <% if job.project.user != current_user %>
                  <div class="btn-abc"><%= link_to "Apply Job", job_user_jobs_path(job), method: :post, class: 'btn btn-primary'  %></div>
                <% end %>

              <% else %>

                <% if user_job.status == "Applied" && user_job.user == current_user %>
                  <div class="badge-status"><p class="badge rounded-pill bg-warning">Status: Applied</p></div>
                <% elsif user_job.status == "Approved" && user_job.user == current_user %>
                  <div class="badge-status"><p class="badge rounded-pill bg-primary">Status: Approved</p></div>
                <% elsif user_job.status == "Confirmed" && user_job.user == current_user %>
                  <div class="badge-status"><p class="badge rounded-pill bg-success">Status: Confirmed</p></div>
                <% elsif user_job.status == "Rejected" && user_job.user == current_user %>
                  <div class="badge-status"><p class="badge rounded-pill bg-danger">Status: Rejected</p></div>
                <% else %>
                <% end %>

              <% end %>

            <% else %>
              <div class="btn-abc"><%= link_to "Apply Job", job_user_jobs_path(job), method: :post, class: 'btn btn-primary'  %></div>
            <% end %>

          </div>
        <% end %>
      </div>
    <% end %>
  <% if current_user == @project.user %>
    <%= link_to "Add Jobs", new_project_job_path(@project), class: 'btn btn-flat'  %>
    <%= link_to "Edit Project", edit_project_path(@project), class: 'btn btn-flat' %>
  <% end %>

  </div>

<%= link_to "Back", root_path, class: 'btn btn-flat'  %>

</div>